name: Java CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          build-root-directory: Cats
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          arguments: build
          build-root-directory: Cats
          gradle-version: 8.6
